### ISSUE TITLE
Type errors

### ISSUE THREAD

**Issue by madpipeline** [expertmm/minetestmapper-python#2]
I'm getting these errors for all the data blocks:

```
Block data: 1c 09 ff ff 02 02 78 9c ed c1 31 01 00 00 00 c2 a0 f5 4f 6d 0c 1f a0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 80 b7 01 40 00 00 01 78 9c 63 00 00 00 01 00 01 00 00 00 ff ff ff ff 00 00 01 00 00 00 06 69 67 6e 6f 72 65 0a 00 00 
Data after node metadata: 
Traceback (most recent call last):
  File "./minetestmapper.py", line 722, in <module>
    static_object_version = readU8(f)
  File "./minetestmapper.py", line 127, in readU8
    return ord(f.read(1))
TypeError: ord() expected a character, but string of length 0 found
Error at (38,-7,-22): ord() expected a character, but string of length 0 found
Block data: 1c 09 ff ff 02 02 78 9c ed c1 31 01 00 00 00 c2 a0 f5 4f 6d 0c 1f a0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 80 b7 01 40 00 00 01 78 9c 63 00 00 00 01 00 01 00 00 00 ff ff ff ff 00 00 01 00 00 00 06 69 67 6e 6f 72 65 0a 00 00 
Data after node metadata: 
Traceback (most recent call last):
  File "./minetestmapper.py", line 722, in <module>
    static_object_version = readU8(f)
  File "./minetestmapper.py", line 127, in readU8
    return ord(f.read(1))
TypeError: ord() expected a character, but string of length 0 found
Error at (38,-8,-22): ord() expected a character, but string of length 0 found
Block data: 1c 09 ff ff 02 02 78 9c ed c1 31 01 00 00 00 c2 a0 f5 4f 6d 0c 1f a0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 80 b7 01 40 00 00 01 78 9c 63 00 00 00 01 00 01 00 00 00 ff ff ff ff 00 00 01 00 00 00 06 69 67 6e 6f 72 65 0a 00 00 
Data after node metadata: 
Traceback (most recent call last):
  File "./minetestmapper.py", line 722, in <module>
    static_object_version = readU8(f)
  File "./minetestmapper.py", line 127, in readU8
    return ord(f.read(1))
TypeError: ord() expected a character, but string of length 0 found
Drawing image
Saving
```

Resulting png file is all white.

Any recommendations?

**Comment by poikilos** [comment]
As far as I know, this happens since the map format changed significantly over time. I disagree with the change, but can't do anything about it. I've sought for help regarding compatibility from the author of minetestmapper-numpy, but didn't get a response. The mapper works on Final Minetest, I think.

**Comment by Poikilos** [comment]
I'm looking into that. I asked the author of minetestmapper-numpy about it, but didn't get a response. I'll discuss it with @OldCoder

**Comment by Poikilos** [comment]
I fixed the exception handling, so I can see what is happening better. Both minetestmapper.py and minetestmapper-numpy.py have the same problem. There are no bytes (such as for the first read, which is static_object_version) in `dec_o.unused_data` where `dec_o` is the `decompressobj`. The issue occurs in both sqlite3 and leveldb (tested using the `--backend leveldb` option with a leveldb world) modes. I don't understand the map format well enough to know why this occurs or fix it, but I'll be working on it. Any help is appreciated.

**Comment by Poikilos** [comment]
The problem happens with some maps such as [stampyworld](https://forums.minetest.org/viewtopic.php?t=8592) (Feb 16, 2014 20:20) but not other maps such as ["Hogwarts & more"](https://forums.minetest.org/viewtopic.php?f=12&t=11291&sid=0e952b3e005737aa64f68cca37011466) (Feb 21, 2015 17:35).
